CREATE TABLE trees.trees
(OBJECTID LONG, WARD VARCHAR(12), ADDNUM VARCHAR(12), ADDSTR VARCHAR(12), LTLOCATION VARCHAR(12), RDLOCATION VARCHAR(15), FACILITY VARCHAR(12), EDGETREE VARCHAR(12), PATHRAIL VARCHAR(12),
SPECIES VARCHAR(50), DBH VARCHAR(12), ARTROAD VARCHAR(12), TREATMENT VARCHAR(15), STREET VARCHAR(50), EABTAGNUM VARCHAR(15), DEDTAGNUM VARCHAR(15), SAP_ID VARCHAR(2555));

LOAD DATA LOCAL INFILE 'D:/Dougall/OpenDataStories/Posts/street_trees/tree-inventory.csv' INTO TABLE trees.trees
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
(OBJECTID, WARD, ADDNUM, ADDSTR, LTLOCATION, RDLOCATION, FACILITY, EDGETREE, PATHRAIL, SPECIES, DBH, ARTROAD, TREATMENT, STREET, EABTAGNUM, DEDTAGNUM, SAP_ID);

CREATE TABLE TREES.PLAN_B AS
SELECT * FROM TREES.trees
WHERE STREET <> "None" and STREET <> "null" and STREET RLIKE '^[A-Z]';

CREATE TABLE TREES.PLAN_B2 AS
SELECT DISTINCT STREET, ADDSTR
FROM TREES.PLAN_B;


#join the unique street names back on the main file to try to build a better street name grouping
CREATE TABLE TREES.TREE_INVENTORY_EXPAND AS
SELECT A.*, B.STREET AS STREET_EXP
FROM
TREES.trees AS A
LEFT OUTER JOIN
TREES.PLAN_B2 AS B
ON A.ADDSTR=B.ADDSTR;




CREATE TABLE TREES.TREE_INVENTORY_EXPAND2 AS
SELECT A.*, B.STREET AS STREET_EXP
FROM
TREES.trees AS A
INNER JOIN
TREES.PLAN_B2 AS B
ON A.ADDSTR=B.ADDSTR;

SELECT * INTO OUTFILE 'D:/Dougall/OpenDataStories/Posts/street_trees/tree-inventory_expand.csv'
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
FROM TREES.TREE_INVENTORY_EXPAND2;
